### ISSUE TITLE
Migrate to Node.js 4.2.2 LTS

### ISSUE THREAD

**Issue by kimar** [LocativeHQ/cloud-app#16]

**Comment by francisdb** [comment]
Should be backwards compatible

**Comment by kimar** [comment]
Not necessarily, Node 4.2.2 ist the official long term supported version so I'd put focus on this one in the first place. I think it's good if we manage to make it backwards compatible, but I don't see a real reason to force it be comptaible to old versions of node.

**Comment by francisdb** [comment]
You totally misunderstood :-) Really have the impression my english is incomprehensible :-)

Just wanted to point out that migration from 0.x to 4.0 should be trivial :-)

**Comment by kimar** [comment]
Ah you mean Node 4.x should be backwards compatible 😊 Sorry wasn't your fault. Haha good we're on the same page.

**Comment by kimar** [comment]
Running in prod now on Node v5.5.0 without any issues :+1:

**Comment by francisdb** [comment]
:+1:
