### ISSUE TITLE
Geofence setup on website does not appear on device

### ISSUE THREAD

**Issue by MrWassen** [LocativeHQ/cloud-app#28]
Please disregard - I just realized that it would need to be imported - sorry!

After setting up a geofence on the web interface and logging into the app using the same account on a device (in this case an iphone 6), the created geofence does not appear on the app.

Should it not appear?

Thx

Dennis

**Comment by francisdb** [comment]
I believe there is a manual sync step on iOS, on Android this is currently not yet implemented.

**Comment by kimar** [comment]
@MrWassen Development of a real sync has already been started on the server side, this will still need to be implemented client-side though.
