### ISSUE TITLE
Add geofences to the public api

### ISSUE THREAD

**Issue by francisdb** [LocativeHQ/cloud-app#3]
I would like to list fences in my app and I think this should be in the public api, same with adding/updating/removing fences.

ps: you might want to move out those routes to a routes.js to make it cleaner
https://github.com/Geofancy/cloud-app/blob/master/app.js

**Comment by kimar** [comment]
The developer portal only documents APIs which are supposed to be publicly accessible. (That being said I'm not sure those are documented a 100% :-P) 

Thank you, good point. I'll also think about a way to make marking APIs private and public a bit more explicit. 

Also almost every endpoint, which protected, should be using oAuth2 rather than propietary session authentication. (In an ideal world) But that's worth another ticket.

**Comment by francisdb** [comment]
@kimar is there a reason that you have a public and a private api?

**Comment by kimar** [comment]
it was (at least). I used this to separate features like adding fencelogs which are added when the app has succeeded/failed a geofence. it shouldnmt be necessarry for users to add those manually as it's just a result an enter/exit event.

**Comment by francisdb** [comment]
@kimar yes, was a bit too fast there. Do you agree on opening up the fence list as GET? (we want to show this in our app)
For the android app I should probably have a look on how the iOS app currently sets up / syncs fences and just use the private api with session stuff?

**Comment by kimar** [comment]
You can already retrieve the fencelogs using the oAuth2 API `/api/v1/fencelogs`. I would really not make the other one public but rather use oAuth2 for any integration. It's not hard at all and brings many benefits.

Here's the description of how to use the oAuth2 API:

https://my.geofancy.com/developer#oauth2-endpoints

**Comment by francisdb** [comment]
I need to show the fences in our app. Since the user will be able to select
what fences to react on...
But if everything works with oauth2 tokens I don't mind using the private
api.

**Comment by kimar** [comment]
Got it, I think we need to clarify two terms used here:

* `Geofences` are always stored locally in the app and can be enabled/disabled. These can, however, be sent to the server for backup/restore scenarios.

* The `Fencelogs` are the result of the server called when entering/leaving fences. `Fencelogs` are basically just a log result.

**Comment by francisdb** [comment]
Fences are fences. Logs are logs.

**Comment by kimar** [comment]
Fair enough, but I'd also agree to say that the nameming might be ambiguous.

**Comment by francisdb** [comment]
I see no problem, in all my conversations I was talking about geofences as in http://www.wikiwand.com/en/Geo-fence :-)

Anyway, so for this ticket I want to get something like ["home", "work", "moms"], ... That way a user of my app can select a fence in a list...

**Comment by kimar** [comment]
I've create a proposal in `android-app` so we can write this down, I'm not a 100% sure if I understood you right (that's my fault) so I'd be pleased if you could have a look at it and edit/add any information needed so I can get this right:

https://github.com/Geofancy/android-app/wiki/Selectable-Geofences

**Comment by francisdb** [comment]
well, no I am confused on my side, let me add some more to that document

**Comment by francisdb** [comment]
Well in fact for me this is not only related to the android app, let me try to get this clear

## 3 systems
 * some service/app: superduper (wants to react on specific fencelogs)
 * geofancy android/ios app
 * geofancy backend

## current situation
`geofancy backend` keeps list of `geofences` (currently the case)
`geofancy backend` lists `geofences` on private api (currently the case)
`geofancy android app` uses this this list to configure the app on one-way sync (to be implemented, already in `geofancy ios app`)

## now to superduper
`superduper` links superduper user to geofancy user using oauth2 (exists)
`geofancy public api` lists `geofences` in public api **TODO**
`superduper` gets those` geofences` and lets user select a `geofence`
`superduper` reacts only on selected `geofences` by filtering the pushed `fencelogs`

## possible next steps
`superduper` allows setting up `geofences`
`geofancy` public api allows posting `geofences`  **TODO**
`geofancy` android/ios app is notified of these new `geofences` and configures them in the app  **TODO**

(android/ios app can be seen as simple agent that is controlled by geofancy backend)
(sounds like the perfect scenario for using something like firebase as sync mechanism)

## concluding

Is this clear?
Would geofancy be willing to be a fit for this scenario?

**Comment by kimar** [comment]
Hi, currently the App only supports local Geofences.
Which means: You start the Android app, add Geofences locally and that's it, the cloud service is just a convenient way to backup your fences. But generally both iOS and Android apps are fully usable without the cloud service. So if you just want to trigger actions on a remote system, I'd start off with getting the app ready and implement connection to the cloud service afterwards. That's how I did it with iOS too.

**Comment by francisdb** [comment]
I know. My question is
    Would geofancy be willing to be a fit for this scenario?

Because that is what I am looking for. Plan to work on the Android app soon.

**Comment by kimar** [comment]
Ah sorry, didn't take `superduper` into account.
Yeah sure, sounds like a good usecase to me. I can implement the oAuth2 that' delivering all existing Geofences.

**Comment by kimar** [comment]
I'd then start by porting the `GET` method for Geofences to oAuth2, is this sufficient for the inital phase?

https://github.com/Geofancy/cloud-app/blob/master/routes/api/geofences.js#L3

**Comment by kimar** [comment]
I think I'll also port `POST` while I'm on it, then we've got everything we need to go bi-directional, there's alsy this *sync* method which is supposed to deliver delta updates of added/removed Geofences, but it's not been thoroughly tested so I'd postpone that one.

**Comment by francisdb** [comment]
That would be great. I will try to have the Android app sending logs to the back end + initially manual sync of geofences

**Comment by kimar** [comment]
In progress here #9
