### ISSUE TITLE
API Authenticate throws Internal server error 500

### ISSUE THREAD

**Issue by GlennVM** [LocativeHQ/cloud-app#30]
I've created an app in the developer center.

Then I tried to authenticate my service with the keys obtained by creating the app.
But I get an Internal Server Error 500 and can't authenticate

**Comment by francisdb** [comment]
@kimar are you tracking these?

**Comment by kimar** [comment]
@francisdb there's a chance this get's dumped to the logs but the odds of finding it are not very high as there's heaps of output.

@GlennVM I've just verified the oAuth 2 API works as expected. The error 500 is intentionally to not expose and critical information. It is likely some missing or misplaced parameter. To try this out you can e.g. create an app and then go to this url:

```
https://my.locative.io/oauth2/authorize?response_type=code&client_id=[your-client-id-here]&redirect_uri=urn:ietf:wg:oauth:2.0:oob
```

Replace `[your-client-id-here]` with your client-id. You should then see a page like this:

![screen shot 2016-03-05 at 8 41 14 am](https://cloud.githubusercontent.com/assets/126418/13541065/4472482e-e2ae-11e5-952a-0939ad9c3adf.png)

After clicking the accept button you'll be redirected to a 404 page as we're using the client-flow (see `redirect_uri` parameter). Please make sure this parameter is the same you've entered when adding the app in the developer center. On you're client you would intercept this request and just look at the url and fetch the `access_token` in the url e.g.:

![screen shot 2016-03-05 at 8 47 58 am](https://cloud.githubusercontent.com/assets/126418/13541201/fba9b02c-e2ae-11e5-8b49-f3c1bad1655f.png)

I think there's also an oAuth implementation which actually redirects to a page with a some javascript and that token, I can have a look into this. But for the time being you'll be redirected to this 404 page when using the `client-flow`. When using the `server-flow` you'll be redirected to you're server's url (as you've entered it).

Hope this helps.

**Comment by francisdb** [comment]
@kimar I guess the only thing to do here is keep track of 500 errors and making sure they end up in some tool similar to https://getsentry.com
@jasperdevrient if you can not reproduce this one please close

**Comment by francisdb** [comment]
@kimar by the way @GlennVM is also an intern here ;-)

**Comment by jasperdevrient** [comment]
@francisdb I can reproduce this, this does only happen when I use the API on my.locative.io but not when I use it locally.

**Comment by jasperdevrient** [comment]
@kimar: I have tried to authenticate (at 14:30 or 1460385000) and I've got the same 500 Internal Server Error.
`
https://my.locative.io/oauth2/authorize?response_type=code&redirect_uri=https%3A%2F%2F7e437cb9.ngrok.io%2Fauthlink%2Flocative%2Fcallback&client_id=[my client id]`

But when I try and run the API on a localhost then the authentication does work.

**Comment by kimar** [comment]
@jasperdevrient @francisdb I've just set up Airbrake but it'll only help us tracking unhandled exceptions for now. I'll try this again, you sure that the `redirect_uri` is definitely correct?

P.S. I'll invite @GlennVM to the org

**Comment by francisdb** [comment]
@kimar if the `redirect_uri ` is incorrect the response should be 400 and not 500

**Comment by kimar** [comment]
@francisdb true, we'll need an issue for this. Also I've hooked up Airbrake as an Express middleware now, this way those errors will also be tracked. I'll get behind it.

**Comment by francisdb** [comment]
@kimar we are stuck on this one so can you have a look?

**Comment by kimar** [comment]
@francisdb yeah I will have a look at it

**Comment by kimar** [comment]
@jasperdevrient @francisdb I've just created a client @ `my.locative.io` using the provided `redirect_uri` and log in works for me... I'm getting reidrected to the ngork uri but it complains about the tunnel being non-existent (which is expected behaviour as it's not existing at this point)

Also as a side-node: You most lileky want to directly acquire a `token` rather than a `code` as a `response_type`.

![screen shot 2016-04-12 at 8 28 02 am](https://cloud.githubusercontent.com/assets/126418/14444402/92a58acc-0088-11e6-8734-c1e4d7c9c833.png)

**Comment by francisdb** [comment]
@kimar if we have another 500 can you look up the trace?

**Comment by kimar** [comment]
@francisdb error are now correctly exposed since https://github.com/LocativeHQ/cloud-app/commit/8bb17a036a420ba5224c6cdb6d47bd67cebf0633

In this particular case the oAuth2 library throws a 403 as the client isn't authorized.
![screen shot 2016-04-12 at 6 59 08 pm](https://cloud.githubusercontent.com/assets/126418/14455273/0f44e614-00e2-11e6-8b83-5cc6c4229d7a.png)

**Comment by kimar** [comment]
@francisdb sure I've just deployed the changes above, if you want to I can also add you to the Airbrake team.

**Comment by francisdb** [comment]
@jasperdevrient can you continue now this is applied? Do you still see 500's?

**Comment by kimar** [comment]
@jasperdevrient I didn't really change logics which altered the behaviour of this, please try gaain and verify the URL is correct. This was most likely the error. If not just get back back to me.

@francisdb In case you want to be added to the Airbrake org, just shoot me your mail address I should add you with to marcus@kida.io

**Comment by jasperdevrient** [comment]
@kimar: It works, there are no more 500 responses.
