### ISSUE TITLE
Global webhook url for push events

### ISSUE THREAD

**Issue by francisdb** [LocativeHQ/cloud-app#31]
For apps integrating locative, currently there are 2 options to get push events for your users.

 - You set up a mqtt connection per user
 - You set up a socket.io connection per user

For each of these you need the username and password of the user, which you in fact don't want to store for security reasons. (that's the whole purpose of using OAUth)
The managing of these subscriptions per user can be tedious and does not scale

I suggest a third one, configuring a single callback url on app level that is triggered for all the users linked to the app. This involves some kind of 'Automatic subscription' when a new user is linked to the app.
This app-global `webhook url` is set up when creating the OAuth app.

eg:
https://dev.netatmo.com/doc/webhooks

Implementation could look like this:

* server receives fencelog from locative app
* server checks if user has oauth apps connected
* for each of the apps check if there is a global callback url set up
* if set do a post to the callback url with as body the fencelog (make sure there is a way to validate that the request is actually coming from locative, see netatmo example)

@kimar what do you think about this?

**Comment by kimar** [comment]
Thanks @francisdb yeah that sounds reasonable. As soon as I find some time I'll take a look into this. :+1:

**Comment by francisdb** [comment]
@kimar I'm going to assign one of our interns on this

**Comment by kimar** [comment]
Cool for sure! Happy to help and to review. Just ping me if you got questions or need help. There's loads of technical debt I wanna get rid of but I'm also working on the iOS App atm.

**Comment by kimar** [comment]
@francisdb if you could create a feature branch for this and give me a heads up when you start I might as well help out / jump into this. I'm currently thinking of getting rid of the proprietary MQTT broker as it's flawed and hard to maintain. Also I'd like to migrate the app over to Heroku which will prevent spawning of custom ports. Albeit I'm not really in favor of maintaining my own version of this broker but rather rely on SaaS ones. It's not being used heavily right now but it's creating lots of load on the database as basically every fencelog is tracked there.

**Comment by francisdb** [comment]
@jasperdevrient is working on this. His pull request should arrive soon.
This has in my eyes nothing to do with MQTT.

**Comment by jasperdevrient** [comment]
@kimar I don't have the suitable permissions to push my changes, could you authorize me or do you prefer I make a fork?

**Comment by kimar** [comment]
@jasperdevrient I've just sent you an invite, feel free to push and raise PRs.

@francisdb I've pretty much finished migrating to Heroku now. Should all be up and running, the Database was bloated with ~ 1 million fencelogs and (partially) huge response outputs, I've cleaned this up a bit, also there's a MongoDB index now active which leads to fencelogs older than 1 year being garbage collected.
