### ISSUE TITLE
Fix travis build

### ISSUE THREAD

**Issue by francisdb** [LocativeHQ/cloud-app#33]
Something is wrong with the travis build

**Comment by kimar** [comment]
The url was for the badge was wrong, it's fixed now. Builds running and should be green soonish. Reminds me of this one https://github.com/LocativeHQ/cloud-app/issues/12 :see_no_evil:

**Comment by francisdb** [comment]
I see travis still builds on pre-4.x node, I thought you switched to 5.x?

**Comment by kimar** [comment]
It's compatible with 5.x but I didn't yet change the `.travis.yml`, I'll address this.
