### ISSUE TITLE
Can't create geofence

### ISSUE THREAD

**Issue by francisdb** [LocativeHQ/cloud-app#44]
On the web app the new geofence page shows `your position`, that should rather be `fence position` and have a different marker since users are used to the my location for that marker.

the user can drag this marker but upon save the location is always `0,0`

It would be nice if there also was some search for a location using geocoding. (like the apps have)

I am sure this used to work before

**Comment by kimar** [comment]
Yeah this definitely used to work, will take a look into this asap.

**Comment by francisdb** [comment]
Ping

**Comment by kimar** [comment]
If I'm lucky I might get to it on the weekend, but can't promise.

**Comment by kimar** [comment]
Fixed in 8263e169301848ebe0454040a842de4fe6f0c4f0 and promoted to `staging` and `prod` by `10:00 AEST`.

**Comment by francisdb** [comment]
thanks
